### ISSUE TITLE
Fix build to include scatterplot dist

### ISSUE THREAD

**Issue by cesgarpas** [governify/dashboard#2]

**Comment by pafmon** [comment]
The only remaining task is signing the plugin.

**Comment by alesancor1** [comment]
The docker/build-push-action is not copying files generated by previous step when building the new image. 

Edit: Solved, plugins were built and signed correctly but stored inside a docker volume that doesn't update on docker-pull. A new environment variable ``` GF_PATHS_PLUGINS``` has been added to docker compose files found in [bluejay infrastructure](https://github.com/governify/bluejay-infrastructure) and [galibo infrastructure](https://github.com/governify/galibo-infrastructure). This new variable sets grafana plugins directory to the specified value. This way, plugins are now copied outside the volume, so the container can be recreated with new plugins by pulling the new dashboard image from DockerHub.
